version: 2
updates:
    # maintains dependencies 
  - package-ecosystem: "pip" 
    directory: "/" 
    schedule:
      interval: "daily"
    assignees:
      - "princenyeche"
    target-branch: "code-review"
    commit-message:
      prefix: "pip"
      include: "scope"
