"""empty message

Revision ID: 00ce4f605e5f
Revises: 27f3307219b1
Create Date: 2021-06-08 22:39:03.790333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ce4f605e5f'
down_revision = '27f3307219b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('confirm_user', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirm_period', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirm_period')
    op.drop_column('user', 'confirm_user')
    op.drop_column('user', 'register_date')
    # ### end Alembic commands ###
